### ISSUE TITLE
hangar.yml spec

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Hangar#465]
So this is what I'm thinking as a spec for a hangar.yml (or hangar.json, or whatever) that a plugin can use to deploy a version with the API.
```yml
project: # Required
  author: Machine_Maker
  name: BestPlugin
version: 3.0.1 # (falls back to platform-specific config)
description: A description # (falls back to platform-specific config)
channel: Release # Cannot create new channels via api deploy
flags:
  - FORUM_SYNC
  - UNSTABLE
  - RECOMMENDED

platforms: # At least 1 required
  PAPER: 
    versions: # At least 1 version required for each platform 
      - 1.15
      - 1.16
    dependencies:
      - name: ProtocolLib # Requried
        required: true # if not present, false
        namespace: # Either namespace OR external-url must be set NOT BOTH
          author: dmulloy2
          name: ProtocolLib
        external-url: https://github.com/dmulloy2/ProtocolLib/releases
```
